title: "Mi Novela Traducida"
description: "Traducciones hechas con amor por Victoria"
baseurl: "" # Dejar vacío para GitHub Page
url: "https://milkybananyan.github.io/traducciones/"
markdown: kramdown

